version: "3.9"

services:
  web:
    build: ./
    image: "indoor_app:latest"
    container_name: web
    restart: on-failure
    expose:
      - "3000"
    volumes:
      - ./testing-data:/usr/app/testing-data
    env_file:
      - .env
    environment:
      - MONGO_URL=${MONGO_URL}
      - POSTGIS_URL=${POSTGIS_URL}
    depends_on:
      - mongo
      - postgis
    networks:
      - backend_network

  # NEW: Nginx reverse proxy
  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    restart: unless-stopped
    ports:
      - "80:80" # HTTP
      - "443:443" # HTTPS (will use after getting certificates)
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
      - ./nginx/certbot-webroot:/var/www/certbot:ro
    depends_on:
      - web
    networks:
      - backend_network

  # NEW: Certbot for SSL certificates
  certbot:
    image: certbot/certbot:latest
    container_name: certbot
    volumes:
      - ./nginx/ssl:/etc/letsencrypt
      - ./nginx/certbot-webroot:/var/www/certbot
    # This will run once and exit - we'll run it manually
    entrypoint: /bin/sh -c "trap exit TERM; while :; do sleep 12h & wait $${!}; certbot renew; done;"

  mongo:
    image: mongo:noble
    container_name: mongodb
    restart: on-failure
    # need to generate keyfile and mount it for replica set authentication
    #(openssl rand -base64 756 > mongo-keyfile
    # chmod 400 mongo-keyfile)
    # command: ["mongod", "--replSet", "rs0", "--keyFile", "/data/keyfile"]

    volumes:
      - ./mongodb-data:/data/db # Bind the volume to a folder in your project
      - ./mongo-init:/docker-entrypoint-initdb.d # Mount init scripts
      # - ./mongo-keyfile:/data/keyfile:ro
    env_file:
      - .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
    ports:
      - "27017:27017"
    networks:
      - backend_network
  # postgis-data:
  postgis:
    image: postgis/postgis:16-master
    container_name: postgis
    restart: on-failure
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432" # Only accessible from host
    volumes:
      - ./postgis-data:/var/lib/postgresql/data
      - ./postgis-init:/docker-entrypoint-initdb.d # Mount init scripts
    networks:
      - backend_network

networks:
  backend_network:
    driver: bridge
